---
title: "TidyTuesdayNinjaWarrior"
author: "Jeff Grayum"
date: "12/22/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading libraries
```{r}
library(tidyverse)
library(tidytuesdayR)
library(scales)
library(ggthemes)
library(tidylo)
library(tidytext)
library(glue)
```

Loading datasets.
```{r}
tuesdata <- tidytuesdayR::tt_load('2020-12-15')

ninja_warrior <- tuesdata$ninja_warrior %>%
  mutate(round_stage = str_remove(round_stage, " \\(Regional/City\\)"))
```

Initial analysis and some data visualization.
```{r}
ninja_warrior %>%
  view()

ninja_warrior %>%
  count(obstacle_name, round_stage, sort = TRUE) %>%
  filter(fct_lump(obstacle_name, 10, w = n, ties.method = "first") != "Other")  %>%
  mutate(obstacle_name = fct_reorder(obstacle_name, n, sum)) %>%
  ggplot(aes(n, obstacle_name, fill = round_stage)) +
  geom_col() +
  labs(title = "The most common Ninja Warrior Obstacles",
       x = "",
       y = "",
       fill = "") +
  theme_fivethirtyeight() +
  theme(text = element_text(family = "Times New Roman")) 

ninja_warrior %>%
  count(location, season) %>%
  filter(fct_lump(location, 10, w = n, ties.method = "first") != "Other") %>%
  mutate(location = fct_reorder(location, n, sum)) %>%
  ggplot(aes(n, location, fill = season)) +
  geom_col() +
  theme_fivethirtyeight() +
  labs(title = "Where are most Ninja Warrior events held?",
       x = "",
       y = "",
       fill = "Season") +
  theme(text = element_text(family = "Times New Roman")) +
  scale_fill_continuous(breaks = 1:10)
 
```


```{r}
ninja_warrior %>%
  count(round_stage, obstacle_name, sort = TRUE)

ninja_warrior %>%
  filter(location == "Venice") %>%
  view()

ninja_warrior %>%
  count(round_stage, sort = TRUE)

ninja_warrior %>%
  count(location, round_stage) %>%
  view()

#What's the distribution of the obstacles?
ninja_warrior %>%
  filter(str_detect(round_stage, "National")) %>%
  count(season, location, round_stage) %>%
  ggplot(aes(n, fill = round_stage)) +
  geom_histogram() +
  scale_x_continuous(breaks = 1:10) 

ninja_warrior %>%
  count(round_stage, sort = TRUE)
```
 
Are there obstacles that are more common during qualifying vs final rounds? Use Tidylo (tidy log odds) package!
```{r}
ninja_warrior %>%
  filter(round_stage %in% c("Qualifying", "Finals")) %>%
  count(round_stage, obstacle_name, sort = TRUE) %>%
  bind_log_odds(round_stage, obstacle_name, n) %>%
  arrange(desc(log_odds_weighted)) %>%
  filter(round_stage == "Finals") %>%
  top_n(16, abs(log_odds_weighted)) %>%
  mutate(obstacle_name = fct_reorder(obstacle_name, log_odds_weighted)) %>%
  ggplot(aes(log_odds_weighted, obstacle_name)) +
  geom_col() +
  labs(x = "More/less likely to appear in finals",
       y = "",
       title = "Liklihood of various Ninja Warrior obstacles appearing in finals") +
  theme_fivethirtyeight() +
  theme(text = element_text(family = "Times New Roman"),
        axis.title = element_text())
```

```{r}

total_rounds <- ninja_warrior %>%
  filter(round_stage == "Qualifying") %>%
  distinct(season, location) %>%
  nrow()
  
  
ninja_warrior %>%
  filter(round_stage %in% c("Qualifying", "Finals")) %>%
  unite(season_location, season, location, remove = FALSE) %>%
  group_by(round_stage) %>%
  mutate(total_rounds = n_distinct(season_location)) %>%
  group_by(round_stage, obstacle_name) %>%
  summarize(avg_position = mean(obstacle_order),
            n_rounds = n(),
            pct_rounds = n_rounds / first(total_rounds)) %>%
  arrange(desc(n_rounds)) %>%
  top_n(10, n_rounds) %>%
  ungroup() %>%
  mutate(obstacle_name = reorder_within(obstacle_name, avg_position, round_stage)) %>%
  ggplot(aes(avg_position, obstacle_name, size = pct_rounds)) +
  geom_point() +
  facet_wrap(~ round_stage, nrow = 2, scales = "free_y") +
  scale_y_reordered() +
  scale_x_continuous(breaks = 1:10) +
  scale_size_continuous(labels = percent) +
  labs(x = "Average position",
       y = "Obstacle name",
       title = "The average position of the most common obstacles in Ninja Warrior",
       subtitle = "Showing the ten most common obstacles in the qualifying and final rounds",
       size = "% of courses") +
  theme_fivethirtyeight() +
  theme(text = element_text(family = "Times New Roman"),
        axis.title = element_text())

ninja_warrior %>%
  filter(round_stage == "Qualifying") %>%
  count(season, location)
```


```{r}
ninja_warrior %>%
  filter(round_stage ==  "Qualifying") %>%
  mutate(obstacle_name = fct_lump(obstacle_name, 10)) %>%
  mutate(obstacle_name = fct_reorder(obstacle_name, obstacle_order)) %>%
  count(obstacle_name, obstacle_order) %>%
  ggplot(aes(obstacle_order, n, fill = obstacle_name)) +
  geom_col() +
  scale_x_continuous(breaks = 1:7) +
  theme_fivethirtyeight() +
  theme(text = element_text(family = "Times New Roman"), 
        axis.title = element_text()) +
  labs(x = "Obstacle order",
       y = "Number of courses", 
       fill = "Obstacle",
       title = "The most common obstacles in each position of the qualifying round of Ninja Warrior")


#The same graph, but showing percent of rounds rather than n(rounds)
ninja_warrior %>%
  filter(round_stage ==  "Qualifying") %>%
  add_count(obstacle_order, round_stage, name = "round_stage_total") %>%
  filter(round_stage_total >= 10) %>%
  mutate(obstacle_name = fct_lump(obstacle_name, 10)) %>%
  mutate(obstacle_name = fct_reorder(obstacle_name, obstacle_order)) %>%
  count(round_stage_total, obstacle_name, obstacle_order) %>%
  ggplot(aes(obstacle_order, n / round_stage_total, fill = obstacle_name)) +
  geom_col() +
  scale_y_continuous(labels = percent) +
  scale_x_continuous(breaks = 1:6) +
  theme_fivethirtyeight() +
  theme(text = element_text(family = "Times New Roman"), 
        axis.title = element_text()) +
  labs(x = "Position",
       y = "Percent of courses", 
       fill = "Obstacle",
       title = "The most common obstacles in each position of the qualifying round of Ninja Warrior")

ninja_warrior %>%
  filter(round_stage ==  "Finals") %>%
  mutate(obstacle_name = fct_lump(obstacle_name, 10)) %>%
  mutate(obstacle_name = fct_reorder(obstacle_name, obstacle_order)) %>%
  count(obstacle_name, obstacle_order) %>%
  ggplot(aes(obstacle_order, n, fill = obstacle_name)) +
  geom_col() +
  scale_x_continuous(breaks = 1:10) +
  theme_fivethirtyeight() +
  theme(text = element_text(family = "Times New Roman"), 
        axis.title = element_text()) +
  labs(x = "Obstacle order",
       y = "Number of courses", 
       fill = "Obstacle",
       title = "The most common obstacles in each position of the final round of Ninja Warrior")

#Let's turn this into a function!
visualize_steps <- function(tbl) {
  tbl %>%
    add_count(obstacle_order, round_stage, name = "round_stage_total") %>%
  filter(round_stage_total >= 10) %>%
  mutate(obstacle_name = fct_lump(obstacle_name, 10)) %>%
  mutate(obstacle_name = fct_reorder(obstacle_name, obstacle_order)) %>%
  count(round_stage_total, obstacle_name, obstacle_order) %>%
  ggplot(aes(obstacle_order, n / round_stage_total, fill = obstacle_name)) +
  geom_col() +
  scale_y_continuous(labels = percent) +
  scale_x_continuous(breaks = 1:10) +
  theme_fivethirtyeight() +
  theme(text = element_text(family = "Times New Roman"), 
        axis.title = element_text()) +
  labs(x = "Position",
       y = "Percent of courses", 
       fill = "Obstacle")
}

#Now let's use the function we wrote to make the same graph we made earlier!
ninja_warrior %>%
  filter(round_stage == "Qualifying") %>%
  visualize_steps() +
  labs(title = "What does a typical Qualifying course look like?")

#And now for the Final round

ninja_warrior %>%
  filter(round_stage == "Finals") %>%
  visualize_steps() +
  labs(title = "What does a typical Finals course look like?") 

ninja_warrior %>%
  filter(round_stage == "National Finals - Stage 1") %>%
  visualize_steps() +
  labs(title = "What does a typical Nations Finals - Stage 1 course look like?")

#Let's go at it w a facet_wrap, eh?
ninja_warrior %>%
  filter(round_stage == "Finals") %>%
  visualize_steps() +
  labs(title = "What does a typical Finals course look like?") +
  facet_wrap(~ obstacle_name) +
  theme(legend.position = "none")
```

```{r}

  ninja_warrior %>%
  filter(round_stage == "Finals") %>%
  add_count(obstacle_order, round_stage, name = "round_stage_total") %>%
  filter(round_stage_total >= 10) %>%
  add_count(obstacle_name, name = "obstacle_total") %>%
  mutate(obstacle_name = glue("{obstacle_name} ({obstacle_total})")) %>%
  mutate(obstacle_name = fct_lump(obstacle_name, 10)) %>%
  mutate(obstacle_name = fct_reorder(obstacle_name, obstacle_order)) %>%
  ggplot(aes(obstacle_order, obstacle_name)) +
  geom_boxplot() +
  scale_x_continuous(breaks = 1:10) +
  theme_fivethirtyeight() +
  theme(text = element_text(family = "Times New Roman"), 
        axis.title = element_text()) +
  labs(x = "Position",
       y = "", 
       title = "The position of the most common obstacles in Ninja Warrior",
       subtitle = "Final round")

```



```{r}
ninja_warrior %>%
  filter(round_stage == "Qualifying",
         obstacle_order <= 6) %>%
  mutate(lumped = fct_lump(obstacle_name, 6),
         lumped = fct_reorder(obstacle_name, obstacle_order + season * 0.01)) %>%
  unite(season_location, season, location, sep = " - ", remove = FALSE) %>%
  mutate(season_location = fct_rev(fct_reorder(season_location, season))) %>%
  ggplot(aes(obstacle_order, season_location, fill = lumped)) +
  geom_tile() +
  geom_text(aes(label = obstacle_name), size = 3) +
  scale_x_continuous(breaks = 1:6) +
  labs(x = "Obstacle order",
       y = "Season and location",
       title = "How have the obstacles varied at each positon over time?",
       subtitle = "Qualifying round") +
  theme_fivethirtyeight() +
  theme(text = element_text(family = "Times New Roman"),
        axis.title = element_text(),
        legend.position = "none")

ninja_warrior %>%
  filter(round_stage == "Finals",
         obstacle_order <= 10) %>%
  mutate(obstacle_name = str_trunc(obstacle_name, 20),
         lumped = fct_lump(obstacle_name, 6),
         lumped = fct_reorder(obstacle_name, obstacle_order + season * 0.01)) %>%
  unite(season_location, season, location, sep = " - ", remove = FALSE) %>%
  mutate(season_location = fct_rev(fct_reorder(season_location, season))) %>%
  ggplot(aes(obstacle_order, season_location, fill = lumped)) +
  geom_tile() +
  geom_text(aes(label = obstacle_name), size = 3) +
  scale_x_continuous(breaks = 1:10) +
  labs(x = "Obstacle order",
       y = "Season and location",
       title = "How have the obstacles varied at each positon over time?",
       subtitle = "Finals round") +
  theme_fivethirtyeight() +
  theme(text = element_text(family = "Times New Roman"),
        axis.title = element_text(),
        legend.position = "none")
```


```{r}
ninja_warrior %>%
  filter(round_stage == "Qualifying") %>%
  mutate(obstacle_name = fct_lump(obstacle_name, 15)) %>%
  mutate(obstacle_name = fct_reorder(obstacle_name, season)) %>%
  ggplot(aes(season, obstacle_name)) +
  geom_boxplot() +
  labs(x = "Season",
       y = "Obstacle",
       title = "How common were various obstacle in each season?") +
  theme_fivethirtyeight() +
  scale_x_continuous(breaks = 1:10) +
  theme(text = element_text(family = "Times New Roman"),
        axis.title = element_text())

ninja_warrior %>%
  filter(round_stage == "Qualifying") %>%
  mutate(obstacle_name = fct_lump(obstacle_name, 8)) %>%
  mutate(obstacle_name = fct_rev(fct_reorder(obstacle_name, season))) %>%
  count(obstacle_name, season) %>%
  group_by(season) %>%
  mutate(pct = n / sum(n)) %>%
  ggplot(aes(season, pct, fill = obstacle_name)) +
  geom_col() +
  labs(x = "Season",
       y = "",
       title = "How common were various obstacle in each season?") +
  theme_fivethirtyeight() +
  scale_x_continuous(breaks = 1:10) +
  theme(text = element_text(family = "Times New Roman"),
        axis.title = element_text()) +
  scale_y_continuous(labels = percent)
```
```

